name: myapp

services:
  web1:
    image: nginx
    volumes:
      - ./front/html/web1.html:/usr/share/nginx/html/index.html
    ports:
      - "8080:80" 
  
  web2:
    image: nginx
    volumes:
      - ./front/html/web2.html:/usr/share/nginx/html/index.html
    ports:
      - "9090:80" 
 
  proxy:
    image: nginx
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    depends_on:
      - web1
      - web2

